[project]
authors = ["Matt Wilkie <matt.wilkie@yukon.ca>"]
channels = ["conda-forge"]
name = "Leaflet.BetterFileLayer"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = ">=22.13.0,<22.14"
